CREATE ROLE cso_conversation_app
  LOGIN
  PASSWORD 'cso_conversation_local'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION;

CREATE ROLE cso_integration_app
  LOGIN
  PASSWORD 'cso_integration_local'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION;

CREATE ROLE cso_human_operations_app
  LOGIN
  PASSWORD 'cso_human_operations_local'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION;
